### ISSUE TITLE
Project crashes after several minutes of running

### ISSUE THREAD

**Issue by petkus09** [Guidewire/teamcity_exporter#2]
Hello.
While I'm not familiar with Go, I'm trying to make it work. So far it seems promising, but unfortunately, it crashes after ~10 minutes of running.
Here is [console dump](https://pastebin.com/cSNASJKj) I get. Hope it makes some sense

Here is the line I'm using to launch the project:
`sudo docker run -p 9200:9200 --network=host -v "$PWD:$PWD" -e GOOS=linux -e GOARCH=amd64 golang:1.8 bash -c "go get -v github.com/guidewire/teamcity_exporter; go install github.com/guidewire/teamcity_exporter; teamcity_exporter --config \"$PWD/bin/teamcity.yaml\" --web.listen-address \":9200\""`

**Comment by petkus09** [comment]
[Another more detailed dump](https://pastebin.com/1auSch9U)
This also happens when launching both via docker and building locally

**Comment by petkus09** [comment]
Okay. Here is the dump using debugging via GoLand. It's an issue in sethgrid package
`goroutine 559752 [running]:
runtime.throw(0x925c31, 0x21)
	/usr/lib/go/src/runtime/panic.go:596 +0x95 fp=0xc420cd74d0 sp=0xc420cd74b0
runtime.mapaccess1_faststr(0x8c0580, 0xc42068cb70, 0x913ed0, 0x5, 0xb883e0)
	/usr/lib/go/src/runtime/hashmap_fast.go:217 +0x4cf fp=0xc420cd7530 sp=0xc420cd74d0
net/textproto.MIMEHeader.Get(0xc42068cb70, 0x913ed0, 0x5, 0x0, 0x0)
	/usr/lib/go/src/net/textproto/header.go:35 +0x75 fp=0xc420cd7568 sp=0xc420cd7530
net/http.Header.Get(0xc42068cb70, 0x913ed0, 0x5, 0x0, 0x0)
	/usr/lib/go/src/net/http/header.go:41 +0x3f fp=0xc420cd75a0 sp=0xc420cd7568
net/http.(*persistConn).roundTrip(0xc4213a3440, 0xc42151e280, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/transport.go:1845 +0xbea fp=0xc420cd7858 sp=0xc420cd75a0
net/http.(*Transport).RoundTrip(0xb63fc0, 0xc420de0e00, 0xb63fc0, 0xed320e52c, 0x2a66d4a1)
	/usr/lib/go/src/net/http/transport.go:391 +0x74c fp=0xc420cd7a78 sp=0xc420cd7858
net/http.send(0xc4217ebb00, 0xb319a0, 0xb63fc0, 0xed320e52c, 0x2a66d4a1, 0xb6b300, 0x0, 0x8, 0xc4216a0430, 0x411598)
	/usr/lib/go/src/net/http/client.go:249 +0x162 fp=0xc420cd7b98 sp=0xc420cd7a78
net/http.(*Client).send(0xc420caa6f0, 0xc4217ebb00, 0xed320e52c, 0x2a66d4a1, 0xb6b300, 0xc4216a0430, 0x0, 0x1, 0x45b903)
	/usr/lib/go/src/net/http/client.go:173 +0x108 fp=0xc420cd7c18 sp=0xc420cd7b98
net/http.(*Client).Do(0xc420caa6f0, 0xc4217ebb00, 0xc420800300, 0x0, 0x0)
	/usr/lib/go/src/net/http/client.go:595 +0x254 fp=0xc420cd7d88 sp=0xc420cd7c18
github.com/sethgrid/pester.(*Client).pester.func2(0xc420160d20, 0xc421257250, 0xc4212571e8, 0xc420800300, 0xc421bb9760, 0xc421bb9780, 0xc420caa6f0, 0xc4208002a0, 0x6, 0x912e8d, ...)
	/home/petkus/go/src/github.com/sethgrid/pester/main.go:266 +0x605 fp=0xc420cd7f38 sp=0xc420cd7d88
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420cd7f40 sp=0xc420cd7f38
created by github.com/sethgrid/pester.(*Client).pester
	/home/petkus/go/src/github.com/sethgrid/pester/main.go:311 +0x488`

Issue is partially resolved, when concurrency limit is set to 1
